import SE from './seData'

/**
 * @module MenuData
 * @description 条件データ定義
 */
const MenuData = {
  types: {
    category: '物件種別',
    type: 'checkbox',
    names: ['SE'],
    defaultValues: [
      SE.fr.code,
      SE.ms.code,
      SE.cms.code,
      SE.kr.code,
      SE.ckr.code,
      SE.land.code,
    ],
    values: [
      SE.fr.code,
      SE.ms.code,
      SE.cms.code,
      SE.kr.code,
      SE.ckr.code,
      SE.land.code,
    ],
    labels: [
      SE.fr.text,
      SE.ms.text,
      SE.cms.text,
      SE.kr.text,
      SE.ckr.text,
      SE.land.text,
    ],
  },
  common: {
    rent: [
      {
        category: '賃料・価格',
        type: 'slider',
        names: ['CHINRYOMIN', 'CHINRYOMAX'],
        defaultValues: [0, 999],
        values: {
          min: 0,
          '2.5%': 3,
          '5%': 3.5,
          '7.5%': 4,
          '10%': 4.5,
          '12.5%': 5,
          '15%': 5.5,
          '17.5%': 6,
          '20%': 6.5,
          '22.5%': 7,
          '25%': 7.5,
          '27.5%': 8,
          '30%': 8.5,
          '32.5%': 9,
          '35%': 9.5,
          '37.5%': 10,
          '40%': 11,
          '42.5%': 12,
          '45%': 13,
          '47.5%': 14,
          '50%': 15,
          '52.5%': 16,
          '55%': 17,
          '57.5%': 18,
          '60%': 19,
          '62.5%': 20,
          '65%': 21,
          '67.5%': 22,
          '70%': 23,
          '72.5%': 24,
          '75%': 25,
          '77.5%': 26,
          '80%': 27,
          '82.5%': 28,
          '85%': 29,
          '87.5%': 30,
          '90%': 35,
          '92.5%': 40,
          '95%': 50,
          '97.5%': 100,
          max: 999,
        },
        labels: ['下限なし', '上限なし'],
      },
      {
        category: '賃料・価格',
        type: 'checkbox',
        names: ['CJOKEN'],
        values: ['1', '3', '4', '2'],
        labels: [
          '管理費・共益費込み',
          '礼金なし',
          '敷金・保証金なし',
          '駐車場代込み',
        ],
      },
      {
        category: '面積・間取り',
        type: 'slider',
        names: ['FR_SENYUMENMIN', 'FR_SENYUMENMAX'],
        defaultValues: [0, 999],
        values: {
          min: 0,
          '6.6%': 20,
          '13.2%': 25,
          '19.8%': 30,
          '26.4%': 35,
          '33%': 40,
          '39.6%': 45,
          '46.2%': 50,
          '52.8%': 55,
          '59.4%': 60,
          '66%': 65,
          '72.6%': 70,
          '79.2%': 80,
          '85.8%': 90,
          '92.4%': 100,
          max: 999,
        },
        labels: ['下限なし', '上限なし'],
      },
      {
        category: '面積・間取り',
        type: 'checkbox',
        names: ['CINM'],
        values: [
          '01',
          '02',
          '03',
          '04',
          '05',
          '06',
          '07',
          '08',
          '09',
          '10',
          '11',
          '12',
          '13',
          '14',
        ],
        labels: [
          'ワンルーム',
          '1K',
          '1DK',
          '1LDK',
          '2K',
          '2DK',
          '2LDK',
          '3K',
          '3DK',
          '3LDK',
          '4K',
          '4DK',
          '4LDK',
          '5K以上',
        ],
      },
      {
        category: '築年数',
        type: 'slider',
        names: ['CINCN'],
        defaultValues: [-1],
        values: {
          min: -1,
          '10%': 0,
          '20%': 1,
          '30%': 3,
          '40%': 5,
          '50%': 7,
          '60%': 10,
          '70%': 15,
          '80%': 20,
          '90%': 25,
          max: 30,
        },
        labels: ['指定なし'],
      },
      {
        category: '駅徒歩',
        type: 'slider',
        names: ['ET'],
        defaultValues: [0],
        values: {
          min: 0,
          '14%': 1,
          '28%': 3,
          '42%': 5,
          '56%': 7,
          '70%': 10,
          '84%': 15,
          max: 20,
        },
        labels: ['指定なし'],
      },
      {
        category: '駅徒歩',
        type: 'checkbox',
        names: ['BF'],
        values: ['1'],
        labels: ['バス停徒歩分数も含める'],
      },
    ],
    buy: [
      {
        category: '賃料・価格',
        type: 'slider',
        names: ['KAMIN', 'KAMAX'],
        defaultValues: [0, 99999],
        values: {
          min: 0,
          '5%': 500,
          '10%': 1000,
          '15%': 1500,
          '20%': 2000,
          '25%': 2500,
          '30%': 3000,
          '35%': 3500,
          '40%': 4000,
          '45%': 4500,
          '50%': 5000,
          '55%': 5500,
          '60%': 6000,
          '65%': 6500,
          '70%': 7000,
          '75%': 7500,
          '80%': 8000,
          '85%': 9000,
          '90%': 10000,
          '95%': 12000,
          max: 99999,
        },
        labels: ['下限なし', '上限なし'],
      },
      {
        category: '物件種別',
        type: 'checkbox',
        names: ['KM'],
        defaultValues: ['1'],
        values: ['1'],
        labels: ['価格未定の物件も含める'],
      },
      {
        category: '面積・間取り',
        type: 'slider',
        names: ['MENMIN', 'MENMAX'],
        defaultValues: [0, 999],
        values: {
          min: 0,
          '9%': 20,
          '18%': 25,
          '27%': 30,
          '36%': 40,
          '45%': 50,
          '54%': 60,
          '63%': 70,
          '72%': 80,
          '81%': 90,
          '90%': 100,
          max: 999,
        },
        labels: ['下限なし', '上限なし'],
      },
      {
        category: '面積・間取り',
        type: 'checkbox',
        names: ['M'],
        values: ['1', '2', '3', '4', '5', '6'],
        labels: [
          'ワンルーム',
          '1K/DK/LDK',
          '2K/DK/LDK',
          '3K/DK/LDK',
          '4K/DK/LDK',
          '5K以上',
        ],
      },
      {
        category: '築年数',
        type: 'slider',
        names: ['CN'],
        defaultValues: [0],
        values: {
          min: 0,
          '14%': 3,
          '28%': 5,
          '42%': 10,
          '56%': 15,
          '70%': 20,
          '84%': 25,
          max: 30,
        },
        labels: ['指定なし'],
      },
      {
        category: '駅徒歩',
        type: 'slider',
        names: ['ET'],
        defaultValues: [0],
        values: {
          min: 0,
          '14%': 1,
          '28%': 3,
          '42%': 5,
          '56%': 7,
          '70%': 10,
          '84%': 15,
          max: 20,
        },
        labels: ['指定なし'],
      },
      {
        category: '駅徒歩',
        type: 'checkbox',
        names: ['BF'],
        values: ['1'],
        labels: ['バス停徒歩分数も含める'],
      },
    ],
  },
}

export default MenuData
